language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install xsltproc

before_script:
- "make package"
- python -m SimpleHTTPServer &
- sleep 3
- "./build/sitespeed.io -u http://0.0.0.0:8000/test/server/www/ -o img-csv -b url,js,css,img,cssimg,font,requests,requestswithoutexpires,docsize,pagesize,criticalpath,loadtime,spof,syncjs,ttfb,domains,kbps,maximgsize,totalimgsize,totaljssize,totalcsssize,browserscaledimg,score"
- "./build/sitespeed-junit.io -o build"

script: ./test/test.sh
