language: java

before_script:
- "make package"
- node test/server/file-server.js &
- sleep 3
- "./build/sitespeed.io -u http://127.0.0.1:8080/ -o img"
- "./build/sitespeed-junit.io > junit.xml"

script: ./test/test.sh
