language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install xsltproc

before_script:
- phantomjs --version
- "make build"
- python -m SimpleHTTPServer 8009 &
- sleep 10
- "./build/bin/sitespeed-sites.io -i test/sitespeed-sites.txt"
- "./build/bin/sitespeed.io -u http://localhost:8009/test/server/www/ -o csv -k true"
- "./build/bin/sitespeed-junit.io -o build"

script: ./test/test.sh

after_script:
  - kill `ps aux | grep "python -m SimpleHTTPServer" | grep -v grep | awk '{print $2}'`